
$(document).ready(function () {
    $("#home").click(function () {
        $('#mysection').html("");
        $('#main').hide().html('<div class="mt-[15%] space-y-3"><div class="text-[#ff4a57] text-2xl ">WELCOME!</div><div class="text-white text-3xl">I Am a Web Developer</div><div class="text-white">I&#39;m a Web Developer with extensive experience. My expertise is to create and design websites.</div></div><div class="bg-[#1f243f]"><div class="p-10"><img src="https://media-exp1.licdn.com/dms/image/C5603AQGnvVYPbvH1JQ/profile-displayphoto-shrink_800_800/0/1615780830834?e=1671062400&v=beta&t=MQ8T1ZY7zUmnvsykgYuOqzklChbKc8Km4nS3YgRRWtg"class="rounded-2xl" alt=""></div></div>').fadeIn(1500);
    });
    $('#about').click(function(){
        $("#main").html("");
        $('#mysection').hide().html('<section id="about" class="flex space-x-5 justify-center"><div><img class="w-[50%]" src="image.jpg" alt=""></div><div class="text-white"><div><div class="m-5 text-3xl">Hello, I am Arnold</div><div class=" w-96 m-5 text-justify">I&#39;m Currently pursuing my B.Tech in Computer Science Engineering with Specialization in Artificial Intelligence whilst working as Head of Corporate Relations at E-Cell Karunya, a student run organization focused on promoting Entrepreneurial mindset among students. My niches are Artificial Intelligence and Cybersecurity.</div> </div> <div class="flex"><div class="m-5"><ul class="space-y-7"><li>Name</li> <li>Age</li><li>Address</li><li>Phone No.</li><li>Email</li></ul></div><div class="m-5"><ul class="space-y-7"><li>P. Arnold Anand</li><li>20</li><li>Hyderabad, Telangana</li><li><a href="tel:+91 00000000">+91 00000000</a></li><li><a href="mailto:pagadalaarnold@karunya.edu.in">pagadalaarnold@karunya.edu.in</a></li></ul></div></div></div></div></section>').fadeIn(1500);
    })
    $('#experience').click(function(){
        $("#main").html("");
        $('#mysection').hide().html('<section id="experience" class=""><div class="text-3xl text-[#ff4a57]">Experience</div><div class="text-white space-y-3 py-3"><div class="text-xl">Senior Human Resources Coordinator</div><div>Karunya Innovation and Incubation Center</div><div>Oct 2021 - Present</div></div><div class="text-white space-y-3 py-3"><div class="text-xl">Senior Corporate Relations Coordinator</div><div>Karunya Innovation and Incubation Center</div><div>Nov 2021 - Present</div></div><div class="text-white space-y-3 py-3"><div class="text-xl">Instructor</div><div>Karunya Hacks</div><div>Jan 2022 - Present</div></div><div class="text-white space-y-3 py-3"><div class="text-xl">Human Resources Coordinator</div><div>Karunya Innovation and Incubation Center</div><div>Nov 2020 - Oct 2021</div></div><div class="text-white space-y-3 py-3"><div class="text-xl">Instructor</div><div>CampK12</div><div>Internship Jun 2022 - Jul 2022</div></div></section>').fadeIn(1500);
    });
    $('#projects').click(function(){
        $("#main").html("");
        $('#mysection').hide().html('<section id="projects"><div class="text-3xl text-[#ff4a57]">Projects</div><div class="grid grid-cols-4 gap-5"><div class="p-4 border border-[#ff4a57] w-72 h-88 space-y-16"><div class="text-2xl text-white">Face Recognition Based Attendance</div><div class="text-white">Technologies/Libraries:<ul><li>Python</li><li>Dlib</li><li>MongoDB</li></ul></div><div class="text-justify text-white">Face Recognition Based Attendance system that can write to the DB after processing the face of the person</div></div><div class="p-4 border border-[#ff4a57] w-72 h-88 space-y-20"><div class="text-2xl text-white">Pedestrian Tracker</div><div class="text-white">Technologies/Libraries:<ul class="py-2"><li>Intel Open Vino</li></ul></div><div class="text-justify text-white">Pedestrian Tracking scenario: it reads frames from an input video sequence, detects pedestrians in the frames, and builds trajectories of movement of the pedestrians in a frame-by-frame manner, using Intel OpenVino.</div></div><div class="p-4 border border-[#ff4a57] w-72 h-88 space-y-10"><div class="text-2xl text-white">Social Distancing Tracker</div><div class="text-white">Technologies/Libraries:<ul class="py-2"><li>Python</li><li>Intel OpenVino</li><li>Cmake</li></ul></div><div class="text-justify text-white">Social distance application that detects people and measures thedistance between them using Intel Openvino. If this distance is less than a value previously provided by the user, then an alert is triggered.</div></div><div class="p-4 border border-[#ff4a57] w-72 h-88 space-y-3"><div class="text-2xl text-white">Smart Garden</div><div class="text-white">Technologies/Libraries:<ul class="py-2"><li>ESP8266</li><li>Intel OpenVino</li><li>AsyncElegantOTA</li><li>Blynk IOT</li><li>Things Speak Cloud</li></ul></div><div class="text-justify text-white">IOT based project that can display the readings of Temperature, Humidity and soil moisture on the cloud platform as well as blynk app wherein in plants can be watered automatically or manually based on set threshold of the soil moisture percentage. The module can also accept Over the Air (OTA) updates if any.</div></div></div></section>').fadeIn(1500);
    });
    $('#contact').click(function(){
        $("#main").html("");
        $('#mysection').hide().html('<section id="contact"><div class="flex justify-center"><button class="border-[#ff4a57] border-2 rounded-full w-60 h-20 text-white hover:bg-[#1f243f]"><a href="mailto:pagadalaarnold@karunya.edu.in">Write to me!</a></button></div><div class="flex justify-center space-x-10 py-10"><div class="hover:scale-110"><a href="https://www.linkedin.com/in/arnold-anand/"><img src="https://img.icons8.com/color/48/000000/linkedin-2--v1.png" /></a></div><div class="hover:scale-110"><a href="https://github.com/arnold-anand"><img src="https://img.icons8.com/ios/50/000000/github--v2.png" /></a></div><div class="hover:scale-110"><a href="https://ctckt.github.io"><img src="https://img.icons8.com/external-flaticons-lineal-color-flat-icons/64/000000/external-www-web-hosting-flaticons-lineal-color-flat-icons.png" /></a> </div></div></section>').fadeIn(1500);
    });
});
